<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;netstandard2.0</TargetFrameworks>
    <RootNamespace>NetToCXSim.Core</RootNamespace>
    <AssemblyName>NetToCXSim.Core</AssemblyName>
    <Version>0.3.1</Version>
    <Authors>ismaillowkey</Authors>
    <Company>ismaillowkey</Company>
    <Description>Core communication library for Omron CX-Simulator PLC memory access and FINS TCP/UDP server</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
